build: off

os: unstable

branches:
  only:
    - master

skip_tags: true

environment:
  nodejs_version: "8.4.0"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install npm
  - .\node_modules\.bin\npm install

test_script:
  - SET NODE_ENV=production
  - NODE_ENV=production .\node_modules\.bin\npm run compile
